# Generated by Django 5.1.7 on 2025-05-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='app_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
