# Generated by Django 5.2.3 on 2025-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_app_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_company',
            name='passport_series_number_if_yatt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('1', 'Avtosalon'), ('2', 'Avtoehtiyot qismlari')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
