# Generated by Django 5.1.7 on 2025-05-18 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('summ', models.BigIntegerField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('public_token', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('done_deal', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_company', to='users.client_company')),
                ('client_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_person', to='users.client_person')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mahsulot')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_items', to='contracts.contractnew')),
            ],
        ),
        migrations.CreateModel(
            name='ContractContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(blank=True, null=True)),
                ('paragraph_header', models.CharField(blank=True, null=True)),
                ('paragraph_text', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='contracts.contractnew')),
            ],
        ),
        migrations.CreateModel(
            name='StdContractContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdcontexts', to='contracts.contractnew')),
            ],
        ),
    ]
