# Generated by Django 5.1.7 on 2025-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnew',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
