# Generated by Django 5.1.7 on 2025-05-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractnew_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnew',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
