# Generated by Django 5.1.7 on 2025-05-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractnew_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractcontext',
            old_name='paragraph_header',
            new_name='value',
        ),
        migrations.AddField(
            model_name='contractcontext',
            name='key',
            field=models.CharField(blank=True, choices=[('header', 'Paragraf'), ('text', 'Subparagraf')], null=True),
        ),
    ]
