# Generated by Django 5.1.7 on 2025-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_rename_paragraph_header_contractcontext_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcontext',
            name='key',
            field=models.CharField(blank=True, choices=[('header', 'header'), ('text', 'header')], null=True),
        ),
    ]
