# Generated by Django 5.1.7 on 2025-05-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contractcontext_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcontext',
            name='key',
            field=models.CharField(blank=True, choices=[('header', 'header'), ('text', 'text')], null=True),
        ),
        migrations.AlterField(
            model_name='contractcontext',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
