# Generated by Django 5.1.7 on 2025-05-28 15:11

import contracts.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contractcontext_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnew',
            name='paragraph_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=contracts.models.default_paragraph_numbers, size=None),
        ),
        migrations.DeleteModel(
            name='StdContractContext',
        ),
    ]
