# Generated by Django 5.1.7 on 2025-05-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractnew_paragraph_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.CharField(blank=True, max_length=5, null=True)),
                ('paragraph_text', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_contexts', to='contracts.contractnew')),
            ],
        ),
    ]
