# Generated by Django 5.1.7 on 2025-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_additionalagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalagreement',
            name='agreement_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
