# Generated by Django 5.1.7 on 2025-05-28 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_additionalagreement_agreement_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalagreement',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
