# Generated by Django 5.1.7 on 2025-05-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_additionalagreement_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='contracts.contractnew')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.CharField(blank=True, max_length=5, null=True)),
                ('paragraph_text', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('agreement_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_contexts', to='contracts.agreement')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalAgreement',
        ),
    ]
