# Generated by Django 5.1.7 on 2025-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_agreement_agreementcontext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
