# Generated by Django 5.1.7 on 2025-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_agreement_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
