# Generated by Django 5.1.7 on 2025-05-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('default_cost', models.BigIntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
