# Generated by Django 5.2.3 on 2025-07-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mahsulot_created_at_mahsulot_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='cypher_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='measurement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
